# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9de93db38330f6b10b1856682f0dbfb565a9db3ca2e874ca116272894f0c10a58afe83296260080ee4141cbdbd8aeb41ea0d0a1a3540755b5bb52cff48787de

test:
  secret_key_base: c20f8a35dc7824798f0051002fd8b1cc1383f071c003358cf4822d10647071860bc46a38517c4c6c652324271109c511a6c972f8fd9650876cff05ac8fb25af7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
